### ISSUE TITLE
Counter must stop once it goes beyond imports group

### ISSUE THREAD

**Issue by marcusgaius** [baincd/vscode-java-class-imports-folding#1]
In general, the extension works fine, but it breaks the UI if there are trait use imports. My suggestion would be adding control for certain keywords, namely `class`, but any way to indicate the line between imports and body of the code can work, I just think making a list of keywords that stop the loop would be the simplest approach.

**Comment by baincd** [comment]
Can you provide an example? I'm not familiar with a trait use import.

**Comment by marcusgaius** [comment]
It is very similar to the import syntax, the only difference being that it can have short class name if already imported.
[Here](https://github.com/craftcms/cms/blob/5.x/src/base/Element.php#L146) is an example.

**Comment by baincd** [comment]
This extension only supports Java.  Other languages, including PHP, are outside the scope of this extension

**Comment by marcusgaius** [comment]
My bad, I was intending to write it to the fork that deals with PHP. Sorry for wasting your time.

**Comment by baincd** [comment]
@marcusgaius Ah, that makes sense.  Thank you for clearing that up  :-)
